export const ACTIONS = {
    GET_MOVIES_BEGIN: 'GET_MOVIES_BEGIN',
    GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
    GET_MOVIES_ERROR: 'GET_MOVIES_ERROR',

    ADD_MOVIE_BEGIN: 'ADD_MOVIE_BEGIN',
    ADD_MOVIE_SUCCESS: 'ADD_MOVIE_SUCCESS',
    ADD_MOVIE_ERROR: 'ADD_MOVIE_ERROR',

    DELETE_MOVIE_BEGIN: 'DELETE_MOVIE_BEGIN',
    DELETE_MOVIE_SUCCESS: 'DELETE_MOVIE_SUCCESS',
    DELETE_MOVIE_ERROR: 'DELETE_MOVIE_ERROR',

    EDIT_MOVIE_BEGIN: 'EDIT_MOVIE_BEGIN',
    EDIT_MOVIE_SUCCESS: 'EDIT_MOVIE_SUCCESS',
    EDIT_MOVIE_ERROR: 'EDIT_MOVIE_ERROR',

    SET_MOVIE_SELECTED: 'SET_MOVIE_SELECTED',

    SET_EDIT_MODAL_VISIBILITY: 'SET_EDIT_MODAL_VISIBILITY',
    SET_DELETE_MODAL_VISIBILITY: 'SET_DELETE_MODAL_VISIBILITY',
    SET_ADD_MODAL_VISIBILITY: 'SET_ADD_MODAL_VISIBILITY',

    GET_MOVIE_BY_ID: 'GET_MOVIE_BY_ID',
    GET_MOVIE_BY_ID_STARTED: 'GET_MOVIE_BY_ID_STARTED',
    GET_MOVIE_BY_ID_SUCCESS: 'GET_MOVIE_BY_ID_SUCCESS',
    GET_MOVIE_BY_ID_ERROR: 'GET_MOVIE_BY_ID_ERROR',
};
